#?????
server:
  port: 8089
#???????
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shujia?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  mail:
  #smtp服务主机  qq邮箱则为smtp.qq.com
   host: smtp.qq.com
    #服务协议
   protocol: smtp
    # 编码集
   default-encoding: UTF-8
    #发送邮件的账户
   username: 2405458492@qq.com
    #授权码
   password: frnvvosrlaayeagb
   port: 25
   properties:
     from: 2405458492@qq.com
   data:
     redis:
       database: 0
       host: localhost
       post : 6379
#mybatis plus??
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #??mybatis plus ???????????NULL???
      update-strategy: not_empty
logging:
   pattern:
     console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'

